### PR TITLE
xdg compatible user directories

### LINKED ISSUE #21: RFE: proper settings directory
I just built the project on Linux and it looks great so far (cc #5).

However I'm running into an issue with my specific distro (NixOS) which places all applications in a read-only filesystem (for reproducibility and all that).
The result is that *remnant-two-overseer* constantly fails to write the settings since it tries to use the directory from which it is run:

https://github.com/Angelore/remnant-two-overseer/blob/342b904a9f228f6e862a199ba865a65df764febf/RemnantOverseer/Services/SettingsService.cs#L17

Of course this is a *very* niche issue, however I think there is merit in separating the application and its data properly anyway.
Think of multiple users sharing the same installation and overwriting each others settings for instance.
Ideally this path would somehow gather the appropriate user directories, such as `%appdata%/remnant-two-overseer/settings.json` on Windows and the XDG directories `${XDG_CONFIG_HOME}/remnant-two-overseer/settings.json` on Linux (with `XDG_CONFIG_HOME` being `~/.config` if unset).
Of course checking whether the file in the application base directory exists and then either migrating it or using it directly to not invalidate everyone's config would be neat ^^"
As I am not a C# person (despite apparently having packaged C# apps now 🙃) I don't know what the proper way to retrieve those paths would be, however I suspect there is either some built-in method provided by some part of *dotnet* itself, or a library providing that functionality on top of it.

If there is a preferred different way to handle this in the *dotnet* world I'd appreciate any advice of course.

---

<details><summary>Nix related stuff</summary>

For any Nix people wanting to run this, this is my current setup:

```nix
# flake.nix
{
  description = "Remnant Overseer: a companion tool for Remnant 2";

  inputs =
  {
    nixpkgs = {};
  };

  outputs = { self, nixpkgs, ... }:
  {
    overlays = rec
    {
      default = remnant-two-overseer;
      remnant-two-overseer = import ./overlay.nix;
    };
    packages = nixpkgs.lib.pipe nixpkgs.legacyPackages
    [
      (builtins.mapAttrs (_: pkgs: pkgs.extend self.overlays.default))
      (builtins.mapAttrs (_: pkgs: rec { inherit (pkgs) remnant-two-overseer; default = remnant-two-overseer; }))
    ];
  };
}
```

```nix
# default.nix
import <nixpkgs> { overlays = [ (import ./overlay.nix) ]; }
```

```nix
# overlay.nix
final: _prev:
{
  remnant-two-overseer = final.callPackage ./package.nix {};
}
```

```nix
# package.nix
{ lib

, buildDotnetModule
, fetchFromGitHub
, dotnetCorePackages
}:

buildDotnetModule (self:
{
  pname = "remnant-two-overseer";
  version = "1.6.0";
  src = fetchFromGitHub
  {
    owner = "Angelore";
    repo = self.pname;
    rev = "v${self.version}";
    hash = "sha256-XfruC+hyOtBvcVXXEWbTAt4bGB8Vr8su9Dg5jnQ0XUk=";
  };

  projectFile = "RemnantOverseer.sln";
  nugetDeps = ./deps.json;

  dotnet-sdk = dotnetCorePackages.sdk_8_0;
  dotnet-runtime = dotnetCorePackages.runtime_8_0;

  meta =
  {
    description = "Remnant Overseer: a companion tool for Remnant 2";
    mainProgram = "RemnantOverseer";
    homepage = "https://github.com/Angelore/remnant-two-overseer/";
    license = lib.licenses.mit;
  };
})
```

You can then `nix build -f . remnant-two-overseer.fetch-deps && ./result` to build the *deps.json* and then build it normally.

Nix code provided under [Unlicense](https://unlicense.org/), so feel free to copy as you see fit.

</details>

---

*Edit*: entirely forgot, I usually write this in every first issue I open with a project >.<
*Thank you so much* for writing stuff like this, I appreciate it a lot!

### PR DESCRIPTION
**Pull request by benaryorg**
This allows global installations via package managers both on Windows (e.g. chocolatey) as well as Linux and other OSes.

---

~~Above is the commit message verbatim.~~ *It used to be, and now there are multiple commits so I won't try to reproduce them all here.*

Closes #21

**Disclaimer**: this is a draft PR, because it builds on another PR that isn't merged yet and it is still unclear whether this is a good solution in general.
Having this sort of behaviour be a compile-time toggle would be best IMO, however I lack the knowledge on how to do that.
In general the PR is here to refer to it, both in other issues as well as from my packaging code (packaging on NixOS for personal use).

Opinions and code improvement suggestions welcome (feel free to leave a review via GitHub).

### CODE REVIEW

**Comment by benaryorg** [comment]
As per the previous comment (and the incredibly long commit messages), this version does move all of the defaults (except for the save path since that one requires file access) into a [single central location](https://github.com/Angelore/remnant-two-overseer/blob/354ebab45595844bbedf7f539ac6d5b750c8e30d/RemnantOverseer/Models/Settings.cs) while also [removing all of the tedious nullable handling](https://github.com/Angelore/remnant-two-overseer/commit/2289e6c854f05401a403df34577743fcbfc1c4a9#diff-47027b45ff859b4691f59a37419fba06e71cfdcf4e5743b264b2fa5880941b32L363) (since GitHub hates anchors; the bottom half of the *RemnantOverseer/ViewModels/WorldViewModel.cs* diff).

While at it I was also able to remove a few pragmas since the compiler is now happy with the code as-is.

For those who want to test, the previous [AppImage build](https://home-benaryorg.s3.ext.ovh.xn--idk5byd.net/pub/RemnantOverseer-1.6.5.AppImage) has been updated.

Side note; there's an odd [dotnet issue with respects to providing multiple constants](https://redirect.github.com/dotnet/sdk/issues/9562#issuecomment-681150093).

**Comment by benaryorg** [comment]
I threw this into CI, so there should be [automatically built AppImage jobs](https://hydra.cloud.bsocat.net/jobset/testing/remnant-two-overseer#tabs-evaluations) from this branch "rebased" on *master* at all times.
Yes, for some reason the filetype is detected as plaintext, so if you want to download it you have to right-click Download As….

File: RemnantOverseer/Services/Log.cs [hunk 1]
```diff
@@ -22,12 +19,22 @@ public static ILogger Instance
         }
     }
 
+    public static string LogFilePath()
```
Comment (Angelore) [inline RemnantOverseer/Services/Log.cs:22]: If you use a method instead of a property, it should be GetLogFilePath

File: RemnantOverseer/Models/Settings.cs [hunk 2]
```diff
@@ -0,0 +1,60 @@
+﻿using RemnantOverseer.Utilities;
+
+namespace RemnantOverseer.Models;
+
+// contains all the default settings
+public class Settings
```
Comment (Angelore) [inline RemnantOverseer/Models/Settings.cs:6]: I don't quite understand why you decided to split this into two classes.  I would put all fields here as private fields. Having defaults in getters is a good idea, however.

File: RemnantOverseer/Services/SettingsService.cs [hunk 3]
```diff
@@ -36,82 +48,46 @@ private string SettingsPath()
...
+    public Settings Get()
     {
-        string path = SettingsPath();
-        if (File.Exists(path))
-        {
-            // Considering making a toast for this and remaking the file. But I think crashing is more educational
-            string json = File.ReadAllText(path);
-            _settings = JsonSerializer.Deserialize<Settings>(json)!;
-        }
+        return _settings.Result;
```
Comment (Angelore) [inline RemnantOverseer/Services/SettingsService.cs:53]: I don't feel like this is a good approach. Why add a blocking call where you don't expect it (i.e. whoever calls this first) instead of doing a blocking call where you do?

File: RemnantOverseer/Models/Settings.cs (hunk 2 above)
Comment (benaryorg) [reply RemnantOverseer/Models/Settings.cs:6]: This is my first time writing C#, working with dotnet, and dealing with MVVM, so I did read up on a lot of stuff, and the general consensus seemed to be that Models should handle business logic (as would be the case for these defaults IMHO), while the Service takes care of providing the interface to the backend (which in this case would be the file, (de)serialisation included).

At least that's what I gathered.

Splitting off the defaults into a wrapper (i.e. Settings vs. ConfigData) was largely because putting both in the same file and working with serialisation conditions was very noisy and pulled focus away from the single thing that class should do; defaults.

So basically:

- SettingsService: takes a path and provides a consistent interface to sync that file with its (otherwise accessible) singleton Settings
- ConfigData: just for serialisation reasons, fully wrapped by Settings
- Settings: just for the defaults

What I also gathered was that ideally the Service would be designed to be "pure" C# without depending on any of the MVVM stuff to be generically reusable across platforms (i.e. web server applications, desktop applications, etc.) since it does not rely on any framework.
Though I may have fully misunderstood that part.

Please do feel free to correct me in any assumptions, and if you have any pointers to a good intro into the usual language patterns that'd be great too (I largely relied on compiler warnings here).
The same of course applies to all other sections/comments.

File: RemnantOverseer/Services/SettingsService.cs (hunk 3 above)
Comment (benaryorg) [reply RemnantOverseer/Services/SettingsService.cs:53]: I didn't feel like that was a good approach either. I just stuck with it because I didn't have a better one (due to lack of experience).

The goal here was to ensure that most everything is covered via the constructor to eliminate all nullable values since the settings clearly *shouldn't* be nullable.
The problem then was that the constructor of course shouldn't be blocking either (or should it?) and it can't be async (AFAIK, the best I can relate this to is 1.7 Java which I dealt with a decade ago), and `Get()` being async means it's very annoying to use in any of the *OnPropertyChanged* handlers which aren't async (*Command* would have an async variant, but that does forfeit any of the benefits of bidirectional bindings).

I'm really not sure how to handle that case to be honest.

**Comment by benaryorg** [comment]
Huh? Well that was a surprise, I was pretty sure you'd request some changes.

Thank you very much though, and sorry if the code gives you any trouble (maintainability or bug) down the line.
Feel free to ping me though if there are any relevant changes to the code, I'd like to see what improvements I could've made ^^"

And once more, thank y'all very much for maintaining this project and anything related!

**Comment by Angelore** [comment]
I decided that I'd rather merge now and give you the functionality you need, and think more about some of the things I've mentioned later. Most of them are a matter of taste anyway :)
